# Generated by Django 6.0.5 on 2026-06-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
