# Generated by Django 6.0.5 on 2026-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tweet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tweet_images/"),
        ),
    ]
